name: List Dir
description: "List the directory"
author: "pnstack"
inputs:
  dir:
    description: "Directory to list"
    default: "*/"

outputs:
  dir:
    description: "List of directories"    
    value: ${{ steps.list-dir.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - id: "list-dir"
      shell: bash
      # run: echo "dir=$(ls -d ${{ inputs.dir }} | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
      run: echo "dir=hello" >> $GITHUB_OUTPUT