on:
  push:
    branches:
      - main

name: Hello World macos runner

jobs:
  hello:
    name: Hello
    runs-on: flyci-macos-large-latest-m1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello
        run: echo "Hello World"