on:
  push:
    branches:
      - main

name: Test

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello
        uses: pnstack/actions/hello@main
  docker:
    name: Docker action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker action
        uses: pnstack/actions/docker@main
        with:
          who-to-greet: 'Mona the Octocat'
  list-dir:
    name: List Dir
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List Dir
        id: list-dir
        uses: pnstack/actions/list-dir@main

      - name: Echo hello
        run: echo "Hello"
        
      - name: Print Dir
        run: echo "${{ steps.list-dir.outputs.dir }}"